[package]
name = "shared-protocol"
version = "0.1.0"
edition = "2021"
description = "Minimal shared protocol for benchmark communication"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }